# Generated by Django 6.0.5 on 2026-06-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='foto',
        ),
    ]
